server:
  port: 9090

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/wall?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: 20
      # 连接池允许的最大连接数
      maximum-pool-size: 200
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: 3000
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true


com:
  wang:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: xxxxx
    accessKeySecret: xxxxxx
    bucketName: haiyao-wall
    baseUrl: https://haiyao-wall.oss-cn-hangzhou.aliyuncs.com/




